Repository GSG-K3/rooms-booker, pull requests merged in 2020-05, with the labels that each got.

#58 Rooms page
  client/package.json
  client/src/App.js
  client/src/components/Layout/Rooms/Rooms.js
  client/src/components/Layout/Rooms/style.css
  server/app.js
  server/controllers/getAllRooms.js
  server/controllers/index.js
  server/database/queries/getAllRooms.js
  server/index.js
Labels: Done, waiting-review

#68 update the schema and resolve certificate
  package.json
  server/database/db_build.js
  server/database/db_build.sql
  server/database/fake_data.sql
Labels: waiting-review

#63 #63 Search for the event
  client/package.json
  client/src/App.js
  client/src/Images/Serach.png
  client/src/components/Common/SerachEvent/SearchEvent.css
  client/src/components/Common/SerachEvent/SearchEvent.js
  client/src/components/Layout/Event/Event.js
  client/src/components/Layout/Event/event.css
  client/src/components/Layout/Events/Events.js
  client/src/components/Layout/Events/events.css
  server/app.js
Labels: Done

#64 create booking form
  client/src/App.js
  client/src/Images/calendar_icon.png
  client/src/Images/clock_icon.png
  client/src/Images/room_icon.png
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Common/BookingForm/Popup.js
  client/src/components/Common/BookingForm/bookingForm.css
  client/src/components/Common/BookingForm/popup.css
  server/controllers/addEvent.js
  server/controllers/index.js
  server/database/queries/eventPost.js
Labels: in-progress, request-changes

#73 update for readme #65
  README.md
Labels: Done

#70 modify the code #69
  client/package.json
  client/src/App.js
  client/src/components/Common/Header/Header.css
  client/src/components/Common/Header/Header.js
  client/src/components/Common/NavBar/NavBar.css
  client/src/components/Common/NavBar/NavBar.js
  client/src/components/Layout/Events/Events.js
  client/src/components/Layout/Rooms/Rooms.js
  client/src/components/Layout/Rooms/style.css
  client/src/components/Layout/UserHome/UserHome.js
  package.json
Labels: waiting-review

#72 change some names
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Common/BookingForm/Popup.js
  client/src/components/Common/BookingForm/popup.css
  server/controllers/index.js
  server/database/queries/eventPost.js
Labels: Done, waiting-review

#49 create login form with css and login endpoint #31
  client/src/App.js
  client/src/components/Layout/Login/Login.css
  client/src/components/Layout/Login/Login.js
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/login.js
  server/database/queries/getPassword.js
Labels: Done, waiting-review

#74 Create Edit form and function for Events, frontEnd and backEnd #33
  client/src/App.js
  client/src/components/Common/EditEvent/EditEvent.js
  client/src/components/Common/EditEvent/Popup.js
  client/src/components/Common/EditEvent/editEvent.css
  client/src/components/Common/EditEvent/popup.css
  client/src/components/Layout/Login/Login.css
  client/src/components/Layout/Login/Login.js
  client/src/components/Layout/UserHome/UserHome.js
  server/controllers/editEvent.js
  server/controllers/index.js
  server/database/queries/eventEdit.js
Labels: Done, waiting-review

#71 create AvailableRooms an SearchAvailableRooms components, create getA…
  client/package.json
  client/src/App.js
  client/src/Images/addRoom.png
  client/src/Images/search.png
  client/src/components/Layout/AvailableRooms/AvailableRooms.css
  client/src/components/Layout/AvailableRooms/AvailableRooms.js
  client/src/components/Layout/Rooms/Rooms.js
  client/src/components/Layout/SearchAvailableRooms/SearchAvailableRooms.css
  client/src/components/Layout/SearchAvailableRooms/SearchAvailableRooms.js
  server/controllers/getAvailableRooms.js
  server/controllers/index.js
  server/database/db_build.js
  server/database/queries/getAvailableRooms.js
Labels: waiting-review

#77 EventInfo page
  client/src/App.js
  client/src/components/Layout/Event/Event.js
  client/src/components/Layout/Event/event.css
  client/src/components/Layout/EventInfo/EventInfo.js
  client/src/components/Layout/EventInfo/eventInfo.css
  client/src/components/Layout/Events/Events.js
  server/database/queries/getAllEvents.js
Labels: waiting-review

#79 edit json file to solve problem in heroku
  package.json
  server/app.js
Labels: waiting-review

#78 handle errors (front / back)
  client/src/App.js
  client/src/Images/handDown.png
  client/src/Images/roundGear.png
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Errors/Err404/NotFound.js
  client/src/components/Errors/Err404/notFound.css
  client/src/components/Errors/Err500/ServerErr.js
  client/src/components/Errors/Err500/serverErr.css
  client/src/components/Layout/Events/Events.js
  client/src/components/Layout/Rooms/Rooms.js
  client/src/components/Layout/SearchAvailableRooms/SearchAvailableRooms.js
  client/src/components/Layout/UserHome/UserHome.js
  server/controllers/addEvent.js
  server/controllers/errors.js
  server/controllers/getAllEvents.js
  server/controllers/getAllRooms.js
  server/controllers/getAvailableRooms.js
  server/controllers/index.js
  server/controllers/userHome.js
  server/database/queries/eventEdit.js
  server/database/queries/eventPost.js
  server/database/queries/getAllEvents.js
  server/database/queries/getAvailableRooms.js
  server/database/queries/getUserHome.js
Labels: waiting-review

#89 Update style
  client/src/components/Common/Header/Header.css
  client/src/components/Errors/Err404/NotFound.js
  client/src/components/Errors/Err500/ServerErr.js
  client/src/components/Layout/AvailableRooms/AvailableRooms.js
  client/src/components/Layout/SearchAvailableRooms/SearchAvailableRooms.js
  client/src/components/Layout/UserHome/UserHome.js
Labels: waiting-review

#86 modify rooms comp
  client/src/components/Layout/AvailableRooms/AvailableRooms.css
  client/src/components/Layout/AvailableRooms/AvailableRooms.js
  client/src/components/Layout/Rooms/Rooms.js
  client/src/components/Layout/Rooms/style.css
  client/src/components/Layout/SearchAvailableRooms/SearchAvailableRooms.css
  server/controllers/getAllEvents.js
Labels: in-progress

#76 add middleware folder #75
  client/src/components/Layout/Login/Login.js
  client/src/components/Layout/UserHome/UserHome.js
  package.json
  server/controllers/checkUser.js
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/userHome.js
  server/database/queries/getPassword.js
  server/database/queries/getUserHome.js
  server/middlewares/authontication.js
Labels: in-progress

#95 modify availabl rooms style
  client/src/components/Layout/AvailableRooms/AvailableRooms.css
  client/src/components/Layout/AvailableRooms/AvailableRooms.js
  client/src/components/Layout/Events/events.css
  client/src/components/Layout/Rooms/Rooms.js
  client/src/components/Layout/Rooms/style.css
Labels: waiting-review

#93 Authontication for login, edit and booking page #92
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Common/EditEvent/EditEvent.js
  client/src/components/Common/Header/Header.js
  client/src/components/Layout/Login/Login.js
  client/src/components/Layout/UserHome/UserHome.js
Labels: Done

#91 update navbar style
  client/src/components/Common/NavBar/NavBar.css
  client/src/components/Layout/Login/Login.css
  client/src/components/Layout/Login/Login.js
  package.json
Labels: Done, waiting-review

#101 edit font color in input #100
  client/src/components/Common/EditEvent/editEvent.css
Labels: Done

#85 create delete event function #81
  client/src/components/Common/DeleteEvent/DeleteEvent.js
  client/src/components/Common/DeleteEvent/Popup.js
  client/src/components/Common/DeleteEvent/popup.css
  client/src/components/Layout/UserHome/UserHome.js
  client/src/components/Layout/UserHome/userHome.css
  server/controllers/addEvent.js
  server/controllers/deleteEvent.js
  server/controllers/index.js
  server/controllers/userHome.js
  server/database/queries/eventDelete.js
Labels: waiting-review

#103 create logout function #102
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Common/BookingForm/bookingForm.css
  client/src/components/Common/EditEvent/EditEvent.js
  client/src/components/Layout/UserHome/UserHome.js
  client/src/components/Layout/UserHome/userHome.css
  client/src/components/Layout/logout/logout.js
  server/controllers/index.js
  server/controllers/logout.js
Labels: waiting-review

#104 fix post event
  server/controllers/addEvent.js
Labels: waiting-review

#109 add heroku link to raedme
  README.md
Labels: waiting-review

#99 edit style for eventinfo
  client/src/Images/background.jpg
  client/src/components/Layout/Event/Event.js
  client/src/components/Layout/EventInfo/EventInfo.js
  client/src/components/Layout/EventInfo/eventInfo.css
  client/src/components/Layout/UserHome/UserHome.js
  client/src/components/Layout/UserHome/userHome.css
  server/database/queries/getAllEvents.js
Labels: waiting-review

#87 edit booking form #83
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Common/BookingForm/bookingForm.css
  client/src/components/Common/EditEvent/EditEvent.js
  client/src/components/Common/EditEvent/editEvent.css
  client/src/components/Layout/AvailableRooms/AvailableRooms.js
  client/src/components/Layout/Rooms/Rooms.js
  client/src/components/Layout/SearchAvailableRooms/SearchAvailableRooms.js
  server/controllers/addEvent.js
  server/controllers/editEvent.js
  server/database/queries/getAvailableRooms.js
Labels: waiting-review

#114 edit date displayed on booking form and edit date so it stored in 24h system in database
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Common/EditEvent/EditEvent.js
  client/src/components/Layout/Rooms/Rooms.js
Labels: waiting-review
