Repository GSG-K3/rooms-booker, pull requests merged in 2020-04, with the labels that each got.

#19 client folder with hello world
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/index.js
Labels: Done, waiting-review

#35 #34 run server
  .gitignore
  package.json
  server/app.js
  server/index.js
Labels: waiting-review

#38 add eslint #37
  .eslintrc.js
  client/.eslintrc.js
  client/package.json
  package.json
Labels: Done

#44 run the two servers concrrently
  package.json
  server/app.js
  server/index.js
Labels: waiting-review

#47 Header
  client/package.json
  client/src/App.js
  client/src/components/Common/Header/Header.css
  client/src/components/Common/Header/Header.js
  client/src/img/Ellipse 2.jpg
  client/src/img/gsg_logo.jpg
  package.json
Labels: request-changes

#51 userhome component
  client/package.json
  client/src/App.js
  client/src/Images/Edit.png
  client/src/Images/delete.jpg
  client/src/components/Layout/UserHome/UserHome.js
  client/src/components/Layout/UserHome/userHome.css
  server/app.js
  server/controller/index.js
  server/controller/userHome.js
  server/database/db_build.js
  server/database/queries/getUserHome.js
Labels: waiting-review

#48 create navbar component #21
  client/public/index.html
  client/src/App.js
  client/src/components/Common/NavBar/NavBar.css
  client/src/components/Common/NavBar/NavBar.js
  client/src/index.js
  package.json
Labels: waiting-review

#56 #23 Eventpage component
  client/package.json
  client/src/App.js
  client/src/components/Layout/Events/Events.js
  client/src/components/Layout/Events/events.css
  server/app.js
  server/controllers/getAllEvents.js
  server/controllers/index.js
  server/database/queries/getAllEvents.js
Labels: waiting-review
