Repository GSG-K3/rooms-booker, pull requests merged in 2020-06, with the labels that each got.

#131 Solve refresh problem in BookingForm component
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Layout/AvailableRooms/AvailableRooms.js
Labels: waiting-review

#132 add documentation userhome & booking form
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Layout/UserHome/UserHome.js
  server/database/queries/eventDelete.js
  server/database/queries/eventEdit.js
  server/database/queries/eventPost.js
  server/database/queries/getAllEvents.js
Labels: waiting-review

#139 add userId to endpoint for homepage #119
  client/src/App.js
  client/src/components/Common/Header/Header.js
  client/src/components/Layout/Login/Login.js
  server/controllers/login.js
Labels: waiting-review

#147 navbar
  client/src/App.js
  client/src/Images/back12.jpg
  client/src/components/Common/NavBar/NavBar.css
  client/src/components/Common/NavBar/NavBar.js
  client/src/components/Layout/Login/Login.css
Labels: waiting-review

#146 Info style
  client/src/Images/icons8-calendar-64.png
  client/src/Images/icons8-clock-128.png
  client/src/Images/icons8-location-96.png
  client/src/Images/icons8-next-location-24.png
  client/src/Images/icons8-note-48.png
  client/src/Images/icons8-person-60.png
  client/src/components/Layout/EventInfo/EventInfo.js
  client/src/components/Layout/EventInfo/eventInfo.css
Labels: waiting-review

#152 Header Menu
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Common/BookingForm/bookingForm.css
  client/src/components/Common/Header/Header.css
  client/src/components/Common/Header/Header.js
  client/src/components/Layout/Event/event.css
  client/src/components/Layout/UserHome/UserHome.js
  client/src/components/Layout/UserHome/userHome.css
Labels: Done, waiting-review

#150 Split api
  client/public/index.html
  client/src/components/Common/BookingForm/BookingForm.js
  client/src/components/Common/BookingForm/bookingForm.css
  client/src/components/Layout/EventInfo/EventInfo.js
  client/src/components/Layout/GoogleCalendar/Calender.js
  client/src/components/Layout/Rooms/Rooms.js
  package.json
  server/controllers/index.js
Labels: in-progress

#157 solve enviroment variable problem #140
  client/.gitignore
  client/package.json
  client/src/components/Layout/GoogleCalendar/Calender.js
Labels: waiting-review
